Kristen Swerzenski

DSC 540

4 February 2024

## Project Milestone 3: Cleaning and Formatting Web Source

### Introduction

For my web source I chose box office data of different movies from  Box Office Mojo. The tables I am working with are broken up by year and display the top 200 films from the box office each year. Each year has two tables with slightly different information - one with that details information for in-year releases and another for calendar year grosses. I will need specific data from each of these tables, so I will need to read each one in and merge them together. Based onthe stremaing data from my flat-file source, I am also focusing on films that were released between 2018 and 2021 so I will be retriving tables of box office data for each of these years. Each film will have to have the year specified in the data before bringing all of the data tables together into a single data frame.

In [1]:
# Importing necessary packages
import requests
from bs4 import BeautifulSoup
import pandas as pd
import re
pd.set_option('display.max_columns', None)

#### Step 1: Scraping the data and merging each year's tables on a common key

Since I will need to scrape multiple tables from my web source, I will define a function that will scrape the table from the html of my source that I can pass each individual url into:

In [2]:
# Defining a function to scrape a table off of my web source using beautiful soup since multiple tables will need to be scraped
def scrape_table(url):
    response = requests.get(url)
    
    # Checking if the response code is good
    if response.status_code == 200:
        html_content = response.text
        
        # Parsing the HTML
        soup = BeautifulSoup(response.content, 'html.parser')
        
        table = soup.find('table')
        df = pd.read_html(str(table), header=0)[0]
        return df
    
    else: print("Failed to retrieve the webpage.")

##### 2021 Data

In [3]:
url_total_grosses_2021 = "https://www.boxofficemojo.com/year/2021/?grossesOption=totalGrosses"
url_calendar_grosses_2021 = "https://www.boxofficemojo.com/year/2021/?grossesOption=calendarGrosses"

total_grosses_2021 = scrape_table(url_total_grosses_2021)
calendar_grosses_2021 = scrape_table(url_calendar_grosses_2021)

# Merge data frames on the common key of film title ("Release")
# Keeping all data from each table for now and distinguishing columns with different suffixes
merged_2021 = pd.merge(total_grosses_2021, calendar_grosses_2021, on="Release", suffixes=('_total', '_calendar'))

# Display the merged DataFrame
display(merged_2021)

C:\Users\krist\AppData\Local\Temp\ipykernel_17364\3925507584.py:13: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table), header=0)[0]
C:\Users\krist\AppData\Local\Temp\ipykernel_17364\3925507584.py:13: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table), header=0)[0]

,Rank_total,Release,Genre_total,Budget_total,Running Time_total,Gross_total,Max Th,Opening,% of Total,Open Th,Open,Close,Distributor_total,Estimated_total,Rank_calendar,Genre_calendar,Budget_calendar,Running Time_calendar,Gross_calendar,Theaters,Total Gross,Release Date,Distributor_calendar,Estimated_calendar
0,1,Spider-Man: No Way Home,-,-,-,"$804,793,477",4336,"$260,138,569",32.3%,4336,Dec 17,Jun 30,Sony Pictures Releasing,False,1,-,-,-,"$572,984,769",4336,"$804,793,477",Dec 17,Sony Pictures Releasing,False
1,2,Shang-Chi and the Legend of the Ten Rings,-,-,-,"$224,543,292",4300,"$75,388,688",33.6%,4300,Sep 3,-,Walt Disney Studios Motion Pictures,False,2,-,-,-,"$224,543,292",4300,"$224,543,292",Sep 3,Walt Disney Studios Motion Pictures,False
2,3,Venom: Let There Be Carnage,-,-,-,"$213,550,366",4225,"$90,033,210",42.2%,4225,Oct 1,Jan 27,Sony Pictures Releasing,False,3,-,-,-,"$212,609,036",4225,"$213,550,366",Oct 1,Sony Pictures Releasing,False
3,4,Black Widow,-,-,-,"$183,651,655",4275,"$80,366,312",43.8%,4160,Jul 9,-,Walt Disney Studios Motion Pictures,False,4,-,-,-,"$183,651,655",4275,"$183,651,655",Jul 9,Walt Disney Studios Motion Pictures,False
4,5,F9: The Fast Saga,-,-,-,"$173,005,945",4203,"$70,043,165",40.5%,4179,Jun 25,-,Universal Pictures,False,5,-,-,-,"$173,005,945",4203,"$173,005,945",Jun 25,Universal Pictures,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180,190,Ailey,-,-,-,"$204,513",88,"$15,091",7.4%,2,Jul 23,-,Neon,False,196,-,-,-,"$204,513",88,"$204,513",Jul 23,Neon,False
181,192,Groundhog Day2021 Re-release,-,-,-,"$200,989",845,"$85,330",42.5%,845,Jan 29,-,Sony Pictures Classics,False,197,-,-,-,"$200,989",845,"$200,989",Jan 29,Sony Pictures Classics,False
182,193,The Resort,-,-,-,"$191,996",114,"$88,831",46.3%,114,Apr 30,-,Vertical Entertainment,False,198,-,-,-,"$191,996",114,"$191,996",Apr 30,Vertical Entertainment,False
183,194,Kaamelott: First Installment,-,-,-,"$188,000",26,"$188,000",100%,26,Jul 23,-,Paramount Pictures,False,199,-,-,-,"$188,000",26,"$188,000",Jul 23,Paramount Pictures,False
184,196,Earwig and the Witch,-,-,-,"$173,704",430,"$92,029",53%,430,Feb 3,-,GKIDS,False,200,-,-,-,"$173,704",430,"$173,704",Feb 3,GKIDS,False

##### 2020 Data

In [4]:
url_total_grosses_2020 = "https://www.boxofficemojo.com/year/2020/?grossesOption=totalGrosses"
url_calendar_grosses_2020 = "https://www.boxofficemojo.com/year/2020/?grossesOption=calendarGrosses"

total_grosses_2020 = scrape_table(url_total_grosses_2020)
calendar_grosses_2020 = scrape_table(url_calendar_grosses_2020)

# Merge data frames on the common key of film title ("Release")
# Keeping all data from each table for now and distinguishing columns with different suffixes
merged_2020 = pd.merge(total_grosses_2020, calendar_grosses_2020, on="Release", suffixes=('_total', '_calendar'))

# Display the merged DataFrame
display(merged_2020)

C:\Users\krist\AppData\Local\Temp\ipykernel_17364\3925507584.py:13: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table), header=0)[0]
C:\Users\krist\AppData\Local\Temp\ipykernel_17364\3925507584.py:13: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table), header=0)[0]

,Rank_total,Release,Genre_total,Budget_total,Running Time_total,Gross_total,Max Th,Opening,% of Total,Open Th,Open,Close,Distributor_total,Estimated_total,Rank_calendar,Genre_calendar,Budget_calendar,Running Time_calendar,Gross_calendar,Theaters,Total Gross,Release Date,Distributor_calendar,Estimated_calendar
0,1,Bad Boys for Life,-,-,-,"$206,305,244",3775,"$62,504,105",30.3%,3775,Jan 17,-,Sony Pictures Releasing,False,1,-,-,-,"$204,417,855",3775,"$206,305,244",Jan 17,Sony Pictures Releasing,False
1,2,Sonic the Hedgehog,-,-,-,"$148,974,665",4198,"$58,018,348",38.9%,4167,Feb 14,-,Paramount Pictures,False,3,-,-,-,"$146,066,470",4198,"$148,974,665",Feb 14,Paramount Pictures,False
2,3,Birds of Prey,-,-,-,"$84,158,461",4236,"$33,010,017",39.2%,4236,Feb 7,-,Warner Bros.,False,6,-,-,-,"$84,158,461",4236,"$84,158,461",Feb 7,Warner Bros.,False
3,4,Dolittle,-,-,-,"$77,047,065",4155,"$21,844,045",28.4%,4155,Jan 17,-,Universal Pictures,False,7,-,-,-,"$77,047,065",4155,"$77,047,065",Jan 17,Universal Pictures,False
4,5,The Invisible Man,-,-,-,"$70,410,000",3636,"$28,205,665",40.1%,3610,Feb 28,-,Universal Pictures,False,9,-,-,-,"$64,914,050",3636,"$70,410,000",Feb 28,Universal Pictures,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,158,Follow Me,-,-,-,"$167,962",50,"$79,182",47.1%,45,Sep 18,-,Vertical Entertainment,False,196,-,-,-,"$167,962",50,"$167,962",Sep 18,Vertical Entertainment,False
152,159,Extra Ordinary,-,-,-,"$164,346",80,"$82,543",50.2%,32,Mar 6,-,Good Deed Entertainment,False,197,-,-,-,"$164,346",80,"$164,346",Mar 6,Good Deed Entertainment,False
153,160,Palm Springs,-,-,-,"$164,000",66,"$164,000",-,66,Jul 10,-,Neon,True,198,-,-,-,"$164,000",66,"$164,000",Jul 10,Neon,False
154,163,A Call to Spy,-,-,-,"$159,014",79,"$35,098",22.1%,75,Oct 2,-,IFC Films,False,199,-,-,-,"$158,864",79,"$159,014",Oct 2,IFC Films,False
155,165,Love Story50th Anniversary,-,-,-,"$153,504",650,"$87,198",56.8%,650,Feb 9,-,Fathom Events,False,200,-,-,-,"$153,504",650,"$153,504",Feb 9,Fathom Events,False

##### 2019 Data

In [5]:
url_total_grosses_2019 = "https://www.boxofficemojo.com/year/2019/?grossesOption=totalGrosses"
url_calendar_grosses_2019 = "https://www.boxofficemojo.com/year/2019/?grossesOption=calendarGrosses"

total_grosses_2019 = scrape_table(url_total_grosses_2019)
calendar_grosses_2019 = scrape_table(url_calendar_grosses_2019)

# Merge data frames on the common key of film title ("Release")
# Keeping all data from each table for now and distinguishing columns with different suffixes
merged_2019 = pd.merge(total_grosses_2019, calendar_grosses_2019, on="Release", suffixes=('_total', '_calendar'))

# Display the merged DataFrame
display(merged_2019)

C:\Users\krist\AppData\Local\Temp\ipykernel_17364\3925507584.py:13: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table), header=0)[0]
C:\Users\krist\AppData\Local\Temp\ipykernel_17364\3925507584.py:13: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table), header=0)[0]

,Rank_total,Release,Genre_total,Budget_total,Running Time_total,Gross_total,Max Th,Opening,% of Total,Open Th,Open,Close,Distributor_total,Estimated_total,Rank_calendar,Genre_calendar,Budget_calendar,Running Time_calendar,Gross_calendar,Theaters,Total Gross,Release Date,Distributor_calendar,Estimated_calendar
0,1,Avengers: Endgame,-,-,-,"$858,373,000",4662,"$357,115,007",41.6%,4662,Apr 26,Sep 12,Walt Disney Studios Motion Pictures,False,1,-,-,-,"$858,373,000",4662,"$858,373,000",Apr 26,Walt Disney Studios Motion Pictures,False
1,2,The Lion King,-,-,-,"$543,638,043",4802,"$191,770,759",35.3%,4725,Jul 19,Dec 5,Walt Disney Studios Motion Pictures,False,2,-,-,-,"$543,638,043",4802,"$543,638,043",Jul 19,Walt Disney Studios Motion Pictures,False
2,3,Star Wars: Episode IX - The Rise of Skywalker,-,-,-,"$515,202,542",4406,"$177,383,864",34.4%,4406,Dec 20,-,Walt Disney Studios Motion Pictures,False,6,-,-,-,"$390,706,234",4406,"$515,202,542",Dec 20,Walt Disney Studios Motion Pictures,False
3,4,Frozen II,-,-,-,"$477,373,578",4440,"$130,263,358",27.3%,4440,Nov 22,-,Walt Disney Studios Motion Pictures,False,4,-,-,-,"$430,144,682",4440,"$477,373,578",Nov 22,Walt Disney Studios Motion Pictures,False
4,5,Toy Story 4,-,-,-,"$434,038,008",4575,"$120,908,065",27.9%,4575,Jun 21,Dec 5,Walt Disney Studios Motion Pictures,False,3,-,-,-,"$434,038,008",4575,"$434,038,008",Jun 21,Walt Disney Studios Motion Pictures,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168,174,The Art of Self-Defense,-,-,-,"$2,410,914",550,"$114,374",4.7%,7,Jul 12,Aug 8,Bleecker Street Media,False,194,-,-,-,"$2,410,914",550,"$2,410,914",Jul 12,Bleecker Street Media,False
169,175,Arctic2019 Re-release,-,-,-,"$2,410,795",268,"$50,878",2.1%,4,Feb 1,May 9,Bleecker Street Media,False,195,-,-,-,"$2,410,795",268,"$2,410,795",Feb 1,Bleecker Street Media,False
170,176,"My People, My Country",-,-,-,"$2,356,683",83,"$876,001",37.2%,67,Oct 1,Nov 7,-,False,197,-,-,-,"$2,356,683",83,"$2,356,683",Oct 1,-,False
171,177,Super 30,-,-,-,"$2,269,878",317,"$871,256",38.4%,317,Jul 12,-,Reliance Big Pictures,False,199,-,-,-,"$2,269,878",317,"$2,269,878",Jul 12,Reliance Big Pictures,False
172,178,Faustina: Love and Mercy,-,-,-,"$2,243,180",810,-,-,-,Oct 28,-,Fathom Events,False,200,-,-,-,"$2,243,180",810,"$2,243,180",Oct 28,Fathom Events,False

##### 2018 Data

In [6]:
url_total_grosses_2018 = "https://www.boxofficemojo.com/year/2018/?grossesOption=totalGrosses"
url_calendar_grosses_2018 = "https://www.boxofficemojo.com/year/2018/?grossesOption=calendarGrosses"

total_grosses_2018 = scrape_table(url_total_grosses_2018)
calendar_grosses_2018 = scrape_table(url_calendar_grosses_2018)

# Merge data frames on the common key of film title ("Release")
# Keeping all data from each table for now and distinguishing columns with different suffixes
merged_2018 = pd.merge(total_grosses_2018, calendar_grosses_2018, on="Release", suffixes=('_total', '_calendar'))

# Display the merged DataFrame
display(merged_2018)

C:\Users\krist\AppData\Local\Temp\ipykernel_17364\3925507584.py:13: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table), header=0)[0]
C:\Users\krist\AppData\Local\Temp\ipykernel_17364\3925507584.py:13: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table), header=0)[0]

,Rank_total,Release,Genre_total,Budget_total,Running Time_total,Gross_total,Max Th,Opening,% of Total,Open Th,Open,Close,Distributor_total,Estimated_total,Rank_calendar,Genre_calendar,Budget_calendar,Running Time_calendar,Gross_calendar,Theaters,Total Gross,Release Date,Distributor_calendar,Estimated_calendar
0,1,Black Panther,-,-,-,"$700,059,566",4084,"$202,003,951",28.9%,4020,Feb 16,Aug 9,Walt Disney Studios Motion Pictures,False,1,-,-,-,"$700,059,566",4084,"$700,059,566",Feb 16,Walt Disney Studios Motion Pictures,False
1,2,Avengers: Infinity War,-,-,-,"$678,815,482",4474,"$257,698,183",38%,4474,Apr 27,Sep 13,Walt Disney Studios Motion Pictures,False,2,-,-,-,"$678,815,482",4474,"$678,815,482",Apr 27,Walt Disney Studios Motion Pictures,False
2,3,Incredibles 2,-,-,-,"$608,581,744",4410,"$182,687,905",30%,4410,Jun 15,Dec 13,Walt Disney Studios Motion Pictures,False,3,-,-,-,"$608,581,744",4410,"$608,581,744",Jun 15,Walt Disney Studios Motion Pictures,False
3,4,Jurassic World: Fallen Kingdom,-,-,-,"$417,719,760",4485,"$148,024,610",35.4%,4475,Jun 22,Oct 4,Universal Pictures,False,4,-,-,-,"$417,719,760",4485,"$417,719,760",Jun 22,Universal Pictures,False
4,5,Aquaman,-,-,-,"$335,061,807",4184,"$67,873,522",20.3%,4125,Dec 21,Apr 4,Warner Bros.,False,13,-,-,-,"$199,059,824",4184,"$335,061,807",Dec 21,Warner Bros.,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
171,179,"Juliet, Naked",-,-,-,"$3,444,895",467,"$60,886",1.8%,4,Aug 17,Oct 25,Roadside Attractions,False,193,-,-,-,"$3,444,895",467,"$3,444,895",Aug 17,Roadside Attractions,False
172,180,Bad Samaritan,-,-,-,"$3,435,047",2007,"$1,726,868",50.3%,2007,May 4,May 24,Electric Entertainment,False,194,-,-,-,"$3,435,047",2007,"$3,435,047",May 4,Electric Entertainment,False
173,181,7 Days in Entebbe,-,-,-,"$3,326,885",838,"$1,592,645",47.9%,838,Mar 16,Apr 12,Focus Features,False,195,-,-,-,"$3,326,885",838,"$3,326,885",Mar 16,Focus Features,False
174,183,2001: A Space Odyssey2018 Re-release,-,-,-,"$3,236,321",13,"$202,759",6.3%,4,May 18,Jul 15,Warner Bros.,False,197,-,-,-,"$3,236,321",13,"$3,236,321",May 18,Warner Bros.,False
175,184,The Sisters Brothers,-,-,-,"$3,143,056",1141,"$115,575",3.7%,4,Sep 21,Dec 20,Annapurna Pictures,False,200,-,-,-,"$3,143,056",1141,"$3,143,056",Sep 21,Annapurna Pictures,False

#### Step 2: Replacing missing values represented by "-" to NaN

The first step I need to complete is ensuring that missing values are properly represented as such in the data set. From the initial scraping, it appears that instead of missing values being represented as Na, they are represented with a string character "-". I am going to take each merged data set from tables of each of the years that I scraped and replace any cell that only contains the value "-" with NaN.

In [7]:
merged_2021.replace('-', pd.NA, inplace=True)
merged_2020.replace('-', pd.NA, inplace=True)
merged_2019.replace('-', pd.NA, inplace=True)
merged_2018.replace('-', pd.NA, inplace=True)

In [8]:
# Checking to make sure all "-" values appear to be replaced
merged_2021.head()

,Rank_total,Release,Genre_total,Budget_total,Running Time_total,Gross_total,Max Th,Opening,% of Total,Open Th,Open,Close,Distributor_total,Estimated_total,Rank_calendar,Genre_calendar,Budget_calendar,Running Time_calendar,Gross_calendar,Theaters,Total Gross,Release Date,Distributor_calendar,Estimated_calendar
0,1,Spider-Man: No Way Home,<NA>,<NA>,<NA>,"$804,793,477",4336,"$260,138,569",32.3%,4336,Dec 17,Jun 30,Sony Pictures Releasing,False,1,<NA>,<NA>,<NA>,"$572,984,769",4336,"$804,793,477",Dec 17,Sony Pictures Releasing,False
1,2,Shang-Chi and the Legend of the Ten Rings,<NA>,<NA>,<NA>,"$224,543,292",4300,"$75,388,688",33.6%,4300,Sep 3,<NA>,Walt Disney Studios Motion Pictures,False,2,<NA>,<NA>,<NA>,"$224,543,292",4300,"$224,543,292",Sep 3,Walt Disney Studios Motion Pictures,False
2,3,Venom: Let There Be Carnage,<NA>,<NA>,<NA>,"$213,550,366",4225,"$90,033,210",42.2%,4225,Oct 1,Jan 27,Sony Pictures Releasing,False,3,<NA>,<NA>,<NA>,"$212,609,036",4225,"$213,550,366",Oct 1,Sony Pictures Releasing,False
3,4,Black Widow,<NA>,<NA>,<NA>,"$183,651,655",4275,"$80,366,312",43.8%,4160,Jul 9,<NA>,Walt Disney Studios Motion Pictures,False,4,<NA>,<NA>,<NA>,"$183,651,655",4275,"$183,651,655",Jul 9,Walt Disney Studios Motion Pictures,False
4,5,F9: The Fast Saga,<NA>,<NA>,<NA>,"$173,005,945",4203,"$70,043,165",40.5%,4179,Jun 25,<NA>,Universal Pictures,False,5,<NA>,<NA>,<NA>,"$173,005,945",4203,"$173,005,945",Jun 25,Universal Pictures,False

#### Step 3: Changing data type of release dates and closing dates to datetime and ensuring year is specified

In [9]:
# Checking the data types of every column (should be the same for every year)
merged_2021.dtypes

Rank_total                int64
Release                  object
Genre_total              object
Budget_total             object
Running Time_total       object
Gross_total              object
Max Th                   object
Opening                  object
% of Total               object
Open Th                  object
Open                     object
Close                    object
Distributor_total        object
Estimated_total            bool
Rank_calendar             int64
Genre_calendar           object
Budget_calendar          object
Running Time_calendar    object
Gross_calendar           object
Theaters                 object
Total Gross              object
Release Date             object
Distributor_calendar     object
Estimated_calendar         bool
dtype: object

I am going to want to combine all of the data from different years that I scraped into a singular data frame, however I need to ensure that I will know which films came out in what years. Luckily, there are already columns for opening/release dates and closing dates (if available) of each film. I checked the data types of every column above and can see that at the moment both the open and close columns are object types, and at the moment they only contain the month and the day that the film opened. I will need to convert both of these columns to datetime and enter they year, however there is a condition I need to account for in the closing date - if the month of the closing date falls before the month of the opening/release date, the closing date needs to be recorded as the following year of the opening/release date. Since I will need to convert all four of my current data frames, I will first create a function to convert these columns to datetime that takes this condition into account:

In [10]:
"""Defining a function to convert open and close columns to datetime, with a condition that if the month of close falls 
before the month of open the a year would be added to the release year"""
def adjust_year(opening_date, closing_date, year):
    # Returning NaN if there is no closing date
    if closing_date is None:
        return None
    # Extracting month from the opening date from a "month abbreviated day" string
    opening_month = pd.to_datetime(opening_date, format='%b %d').month
    # Extracting month from the closing date from a "month abbreviated day" string
    closing_month = pd.to_datetime(closing_date, format='%b %d').month
    # If the closing month falls before the opening month, increase the specified year by 1
    if closing_month < opening_month:
        return pd.to_datetime(closing_date + ' ' + str(year + 1), format='%b %d %Y')
    # If that is not the case, keep the specified year
    else:
        return pd.to_datetime(closing_date + ' ' + str(year), format='%b %d %Y')

In [11]:
# Using a lambda function to apply the adjust_year function to every row of the data frame
merged_2021['Close'] = merged_2021.apply(lambda row: adjust_year(row['Open'], row['Close'], 2021), axis=1)

# Converting the 'Open' and 'Close' date columns to datetime, appending all in the "Open" column with the year 2021
merged_2021['Open'] = pd.to_datetime(merged_2021['Open'] + ' 2021')
merged_2021['Close'] = pd.to_datetime(merged_2021['Close'])

# Displaying the data frame to check datetime conversions
display(merged_2021)

,Rank_total,Release,Genre_total,Budget_total,Running Time_total,Gross_total,Max Th,Opening,% of Total,Open Th,Open,Close,Distributor_total,Estimated_total,Rank_calendar,Genre_calendar,Budget_calendar,Running Time_calendar,Gross_calendar,Theaters,Total Gross,Release Date,Distributor_calendar,Estimated_calendar
0,1,Spider-Man: No Way Home,<NA>,<NA>,<NA>,"$804,793,477",4336,"$260,138,569",32.3%,4336,2021-12-17,2022-06-30,Sony Pictures Releasing,False,1,<NA>,<NA>,<NA>,"$572,984,769",4336,"$804,793,477",Dec 17,Sony Pictures Releasing,False
1,2,Shang-Chi and the Legend of the Ten Rings,<NA>,<NA>,<NA>,"$224,543,292",4300,"$75,388,688",33.6%,4300,2021-09-03,NaT,Walt Disney Studios Motion Pictures,False,2,<NA>,<NA>,<NA>,"$224,543,292",4300,"$224,543,292",Sep 3,Walt Disney Studios Motion Pictures,False
2,3,Venom: Let There Be Carnage,<NA>,<NA>,<NA>,"$213,550,366",4225,"$90,033,210",42.2%,4225,2021-10-01,2022-01-27,Sony Pictures Releasing,False,3,<NA>,<NA>,<NA>,"$212,609,036",4225,"$213,550,366",Oct 1,Sony Pictures Releasing,False
3,4,Black Widow,<NA>,<NA>,<NA>,"$183,651,655",4275,"$80,366,312",43.8%,4160,2021-07-09,NaT,Walt Disney Studios Motion Pictures,False,4,<NA>,<NA>,<NA>,"$183,651,655",4275,"$183,651,655",Jul 9,Walt Disney Studios Motion Pictures,False
4,5,F9: The Fast Saga,<NA>,<NA>,<NA>,"$173,005,945",4203,"$70,043,165",40.5%,4179,2021-06-25,NaT,Universal Pictures,False,5,<NA>,<NA>,<NA>,"$173,005,945",4203,"$173,005,945",Jun 25,Universal Pictures,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180,190,Ailey,<NA>,<NA>,<NA>,"$204,513",88,"$15,091",7.4%,2,2021-07-23,NaT,Neon,False,196,<NA>,<NA>,<NA>,"$204,513",88,"$204,513",Jul 23,Neon,False
181,192,Groundhog Day2021 Re-release,<NA>,<NA>,<NA>,"$200,989",845,"$85,330",42.5%,845,2021-01-29,NaT,Sony Pictures Classics,False,197,<NA>,<NA>,<NA>,"$200,989",845,"$200,989",Jan 29,Sony Pictures Classics,False
182,193,The Resort,<NA>,<NA>,<NA>,"$191,996",114,"$88,831",46.3%,114,2021-04-30,NaT,Vertical Entertainment,False,198,<NA>,<NA>,<NA>,"$191,996",114,"$191,996",Apr 30,Vertical Entertainment,False
183,194,Kaamelott: First Installment,<NA>,<NA>,<NA>,"$188,000",26,"$188,000",100%,26,2021-07-23,NaT,Paramount Pictures,False,199,<NA>,<NA>,<NA>,"$188,000",26,"$188,000",Jul 23,Paramount Pictures,False
184,196,Earwig and the Witch,<NA>,<NA>,<NA>,"$173,704",430,"$92,029",53%,430,2021-02-03,NaT,GKIDS,False,200,<NA>,<NA>,<NA>,"$173,704",430,"$173,704",Feb 3,GKIDS,False

Now I can take this framework and apply it to the remaining years' data frames:

In [12]:
merged_2020['Close'] = merged_2020.apply(lambda row: adjust_year(row['Open'], row['Close'], 2020), axis=1)

merged_2020['Open'] = pd.to_datetime(merged_2020['Open'] + ' 2020')
merged_2020['Close'] = pd.to_datetime(merged_2020['Close'])

display(merged_2020)

,Rank_total,Release,Genre_total,Budget_total,Running Time_total,Gross_total,Max Th,Opening,% of Total,Open Th,Open,Close,Distributor_total,Estimated_total,Rank_calendar,Genre_calendar,Budget_calendar,Running Time_calendar,Gross_calendar,Theaters,Total Gross,Release Date,Distributor_calendar,Estimated_calendar
0,1,Bad Boys for Life,<NA>,<NA>,<NA>,"$206,305,244",3775,"$62,504,105",30.3%,3775,2020-01-17,NaT,Sony Pictures Releasing,False,1,<NA>,<NA>,<NA>,"$204,417,855",3775,"$206,305,244",Jan 17,Sony Pictures Releasing,False
1,2,Sonic the Hedgehog,<NA>,<NA>,<NA>,"$148,974,665",4198,"$58,018,348",38.9%,4167,2020-02-14,NaT,Paramount Pictures,False,3,<NA>,<NA>,<NA>,"$146,066,470",4198,"$148,974,665",Feb 14,Paramount Pictures,False
2,3,Birds of Prey,<NA>,<NA>,<NA>,"$84,158,461",4236,"$33,010,017",39.2%,4236,2020-02-07,NaT,Warner Bros.,False,6,<NA>,<NA>,<NA>,"$84,158,461",4236,"$84,158,461",Feb 7,Warner Bros.,False
3,4,Dolittle,<NA>,<NA>,<NA>,"$77,047,065",4155,"$21,844,045",28.4%,4155,2020-01-17,NaT,Universal Pictures,False,7,<NA>,<NA>,<NA>,"$77,047,065",4155,"$77,047,065",Jan 17,Universal Pictures,False
4,5,The Invisible Man,<NA>,<NA>,<NA>,"$70,410,000",3636,"$28,205,665",40.1%,3610,2020-02-28,NaT,Universal Pictures,False,9,<NA>,<NA>,<NA>,"$64,914,050",3636,"$70,410,000",Feb 28,Universal Pictures,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,158,Follow Me,<NA>,<NA>,<NA>,"$167,962",50,"$79,182",47.1%,45,2020-09-18,NaT,Vertical Entertainment,False,196,<NA>,<NA>,<NA>,"$167,962",50,"$167,962",Sep 18,Vertical Entertainment,False
152,159,Extra Ordinary,<NA>,<NA>,<NA>,"$164,346",80,"$82,543",50.2%,32,2020-03-06,NaT,Good Deed Entertainment,False,197,<NA>,<NA>,<NA>,"$164,346",80,"$164,346",Mar 6,Good Deed Entertainment,False
153,160,Palm Springs,<NA>,<NA>,<NA>,"$164,000",66,"$164,000",<NA>,66,2020-07-10,NaT,Neon,True,198,<NA>,<NA>,<NA>,"$164,000",66,"$164,000",Jul 10,Neon,False
154,163,A Call to Spy,<NA>,<NA>,<NA>,"$159,014",79,"$35,098",22.1%,75,2020-10-02,NaT,IFC Films,False,199,<NA>,<NA>,<NA>,"$158,864",79,"$159,014",Oct 2,IFC Films,False
155,165,Love Story50th Anniversary,<NA>,<NA>,<NA>,"$153,504",650,"$87,198",56.8%,650,2020-02-09,NaT,Fathom Events,False,200,<NA>,<NA>,<NA>,"$153,504",650,"$153,504",Feb 9,Fathom Events,False

In [13]:
merged_2019['Close'] = merged_2019.apply(lambda row: adjust_year(row['Open'], row['Close'], 2019), axis=1)

merged_2019['Open'] = pd.to_datetime(merged_2019['Open'] + ' 2019')
merged_2019['Close'] = pd.to_datetime(merged_2019['Close'])

display(merged_2019)

,Rank_total,Release,Genre_total,Budget_total,Running Time_total,Gross_total,Max Th,Opening,% of Total,Open Th,Open,Close,Distributor_total,Estimated_total,Rank_calendar,Genre_calendar,Budget_calendar,Running Time_calendar,Gross_calendar,Theaters,Total Gross,Release Date,Distributor_calendar,Estimated_calendar
0,1,Avengers: Endgame,<NA>,<NA>,<NA>,"$858,373,000",4662,"$357,115,007",41.6%,4662,2019-04-26,2019-09-12,Walt Disney Studios Motion Pictures,False,1,<NA>,<NA>,<NA>,"$858,373,000",4662,"$858,373,000",Apr 26,Walt Disney Studios Motion Pictures,False
1,2,The Lion King,<NA>,<NA>,<NA>,"$543,638,043",4802,"$191,770,759",35.3%,4725,2019-07-19,2019-12-05,Walt Disney Studios Motion Pictures,False,2,<NA>,<NA>,<NA>,"$543,638,043",4802,"$543,638,043",Jul 19,Walt Disney Studios Motion Pictures,False
2,3,Star Wars: Episode IX - The Rise of Skywalker,<NA>,<NA>,<NA>,"$515,202,542",4406,"$177,383,864",34.4%,4406,2019-12-20,NaT,Walt Disney Studios Motion Pictures,False,6,<NA>,<NA>,<NA>,"$390,706,234",4406,"$515,202,542",Dec 20,Walt Disney Studios Motion Pictures,False
3,4,Frozen II,<NA>,<NA>,<NA>,"$477,373,578",4440,"$130,263,358",27.3%,4440,2019-11-22,NaT,Walt Disney Studios Motion Pictures,False,4,<NA>,<NA>,<NA>,"$430,144,682",4440,"$477,373,578",Nov 22,Walt Disney Studios Motion Pictures,False
4,5,Toy Story 4,<NA>,<NA>,<NA>,"$434,038,008",4575,"$120,908,065",27.9%,4575,2019-06-21,2019-12-05,Walt Disney Studios Motion Pictures,False,3,<NA>,<NA>,<NA>,"$434,038,008",4575,"$434,038,008",Jun 21,Walt Disney Studios Motion Pictures,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168,174,The Art of Self-Defense,<NA>,<NA>,<NA>,"$2,410,914",550,"$114,374",4.7%,7,2019-07-12,2019-08-08,Bleecker Street Media,False,194,<NA>,<NA>,<NA>,"$2,410,914",550,"$2,410,914",Jul 12,Bleecker Street Media,False
169,175,Arctic2019 Re-release,<NA>,<NA>,<NA>,"$2,410,795",268,"$50,878",2.1%,4,2019-02-01,2019-05-09,Bleecker Street Media,False,195,<NA>,<NA>,<NA>,"$2,410,795",268,"$2,410,795",Feb 1,Bleecker Street Media,False
170,176,"My People, My Country",<NA>,<NA>,<NA>,"$2,356,683",83,"$876,001",37.2%,67,2019-10-01,2019-11-07,<NA>,False,197,<NA>,<NA>,<NA>,"$2,356,683",83,"$2,356,683",Oct 1,<NA>,False
171,177,Super 30,<NA>,<NA>,<NA>,"$2,269,878",317,"$871,256",38.4%,317,2019-07-12,NaT,Reliance Big Pictures,False,199,<NA>,<NA>,<NA>,"$2,269,878",317,"$2,269,878",Jul 12,Reliance Big Pictures,False
172,178,Faustina: Love and Mercy,<NA>,<NA>,<NA>,"$2,243,180",810,<NA>,<NA>,<NA>,2019-10-28,NaT,Fathom Events,False,200,<NA>,<NA>,<NA>,"$2,243,180",810,"$2,243,180",Oct 28,Fathom Events,False

In [14]:
merged_2018['Close'] = merged_2018.apply(lambda row: adjust_year(row['Open'], row['Close'], 2018), axis=1)

merged_2018['Open'] = pd.to_datetime(merged_2018['Open'] + ' 2018')
merged_2018['Close'] = pd.to_datetime(merged_2018['Close'])

display(merged_2018)

,Rank_total,Release,Genre_total,Budget_total,Running Time_total,Gross_total,Max Th,Opening,% of Total,Open Th,Open,Close,Distributor_total,Estimated_total,Rank_calendar,Genre_calendar,Budget_calendar,Running Time_calendar,Gross_calendar,Theaters,Total Gross,Release Date,Distributor_calendar,Estimated_calendar
0,1,Black Panther,<NA>,<NA>,<NA>,"$700,059,566",4084,"$202,003,951",28.9%,4020,2018-02-16,2018-08-09,Walt Disney Studios Motion Pictures,False,1,<NA>,<NA>,<NA>,"$700,059,566",4084,"$700,059,566",Feb 16,Walt Disney Studios Motion Pictures,False
1,2,Avengers: Infinity War,<NA>,<NA>,<NA>,"$678,815,482",4474,"$257,698,183",38%,4474,2018-04-27,2018-09-13,Walt Disney Studios Motion Pictures,False,2,<NA>,<NA>,<NA>,"$678,815,482",4474,"$678,815,482",Apr 27,Walt Disney Studios Motion Pictures,False
2,3,Incredibles 2,<NA>,<NA>,<NA>,"$608,581,744",4410,"$182,687,905",30%,4410,2018-06-15,2018-12-13,Walt Disney Studios Motion Pictures,False,3,<NA>,<NA>,<NA>,"$608,581,744",4410,"$608,581,744",Jun 15,Walt Disney Studios Motion Pictures,False
3,4,Jurassic World: Fallen Kingdom,<NA>,<NA>,<NA>,"$417,719,760",4485,"$148,024,610",35.4%,4475,2018-06-22,2018-10-04,Universal Pictures,False,4,<NA>,<NA>,<NA>,"$417,719,760",4485,"$417,719,760",Jun 22,Universal Pictures,False
4,5,Aquaman,<NA>,<NA>,<NA>,"$335,061,807",4184,"$67,873,522",20.3%,4125,2018-12-21,2019-04-04,Warner Bros.,False,13,<NA>,<NA>,<NA>,"$199,059,824",4184,"$335,061,807",Dec 21,Warner Bros.,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
171,179,"Juliet, Naked",<NA>,<NA>,<NA>,"$3,444,895",467,"$60,886",1.8%,4,2018-08-17,2018-10-25,Roadside Attractions,False,193,<NA>,<NA>,<NA>,"$3,444,895",467,"$3,444,895",Aug 17,Roadside Attractions,False
172,180,Bad Samaritan,<NA>,<NA>,<NA>,"$3,435,047",2007,"$1,726,868",50.3%,2007,2018-05-04,2018-05-24,Electric Entertainment,False,194,<NA>,<NA>,<NA>,"$3,435,047",2007,"$3,435,047",May 4,Electric Entertainment,False
173,181,7 Days in Entebbe,<NA>,<NA>,<NA>,"$3,326,885",838,"$1,592,645",47.9%,838,2018-03-16,2018-04-12,Focus Features,False,195,<NA>,<NA>,<NA>,"$3,326,885",838,"$3,326,885",Mar 16,Focus Features,False
174,183,2001: A Space Odyssey2018 Re-release,<NA>,<NA>,<NA>,"$3,236,321",13,"$202,759",6.3%,4,2018-05-18,2018-07-15,Warner Bros.,False,197,<NA>,<NA>,<NA>,"$3,236,321",13,"$3,236,321",May 18,Warner Bros.,False
175,184,The Sisters Brothers,<NA>,<NA>,<NA>,"$3,143,056",1141,"$115,575",3.7%,4,2018-09-21,2018-12-20,Annapurna Pictures,False,200,<NA>,<NA>,<NA>,"$3,143,056",1141,"$3,143,056",Sep 21,Annapurna Pictures,False

#### Step 4: Combining tables into a single data frame

Now that the films in each data frame can be distinguished by the year that they were released, I can combine all of them into a singular data frame to work with from here. To do this, I will concatenate them together using pd.concat():

In [15]:
# Defining a list of all of the dataa frames I want to combine
all_dfs = [merged_2021, merged_2020, merged_2019, merged_2018]
# Using pd.concat() to concatenate all data together, ignoring the index since it is not relevant at the moment
boxoffice_df = pd.concat(all_dfs, ignore_index=True)
# Checking the concatenated data frame
boxoffice_df

,Rank_total,Release,Genre_total,Budget_total,Running Time_total,Gross_total,Max Th,Opening,% of Total,Open Th,Open,Close,Distributor_total,Estimated_total,Rank_calendar,Genre_calendar,Budget_calendar,Running Time_calendar,Gross_calendar,Theaters,Total Gross,Release Date,Distributor_calendar,Estimated_calendar
0,1,Spider-Man: No Way Home,<NA>,<NA>,<NA>,"$804,793,477",4336,"$260,138,569",32.3%,4336,2021-12-17,2022-06-30,Sony Pictures Releasing,False,1,<NA>,<NA>,<NA>,"$572,984,769",4336,"$804,793,477",Dec 17,Sony Pictures Releasing,False
1,2,Shang-Chi and the Legend of the Ten Rings,<NA>,<NA>,<NA>,"$224,543,292",4300,"$75,388,688",33.6%,4300,2021-09-03,NaT,Walt Disney Studios Motion Pictures,False,2,<NA>,<NA>,<NA>,"$224,543,292",4300,"$224,543,292",Sep 3,Walt Disney Studios Motion Pictures,False
2,3,Venom: Let There Be Carnage,<NA>,<NA>,<NA>,"$213,550,366",4225,"$90,033,210",42.2%,4225,2021-10-01,2022-01-27,Sony Pictures Releasing,False,3,<NA>,<NA>,<NA>,"$212,609,036",4225,"$213,550,366",Oct 1,Sony Pictures Releasing,False
3,4,Black Widow,<NA>,<NA>,<NA>,"$183,651,655",4275,"$80,366,312",43.8%,4160,2021-07-09,NaT,Walt Disney Studios Motion Pictures,False,4,<NA>,<NA>,<NA>,"$183,651,655",4275,"$183,651,655",Jul 9,Walt Disney Studios Motion Pictures,False
4,5,F9: The Fast Saga,<NA>,<NA>,<NA>,"$173,005,945",4203,"$70,043,165",40.5%,4179,2021-06-25,NaT,Universal Pictures,False,5,<NA>,<NA>,<NA>,"$173,005,945",4203,"$173,005,945",Jun 25,Universal Pictures,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
685,179,"Juliet, Naked",<NA>,<NA>,<NA>,"$3,444,895",467,"$60,886",1.8%,4,2018-08-17,2018-10-25,Roadside Attractions,False,193,<NA>,<NA>,<NA>,"$3,444,895",467,"$3,444,895",Aug 17,Roadside Attractions,False
686,180,Bad Samaritan,<NA>,<NA>,<NA>,"$3,435,047",2007,"$1,726,868",50.3%,2007,2018-05-04,2018-05-24,Electric Entertainment,False,194,<NA>,<NA>,<NA>,"$3,435,047",2007,"$3,435,047",May 4,Electric Entertainment,False
687,181,7 Days in Entebbe,<NA>,<NA>,<NA>,"$3,326,885",838,"$1,592,645",47.9%,838,2018-03-16,2018-04-12,Focus Features,False,195,<NA>,<NA>,<NA>,"$3,326,885",838,"$3,326,885",Mar 16,Focus Features,False
688,183,2001: A Space Odyssey2018 Re-release,<NA>,<NA>,<NA>,"$3,236,321",13,"$202,759",6.3%,4,2018-05-18,2018-07-15,Warner Bros.,False,197,<NA>,<NA>,<NA>,"$3,236,321",13,"$3,236,321",May 18,Warner Bros.,False
689,184,The Sisters Brothers,<NA>,<NA>,<NA>,"$3,143,056",1141,"$115,575",3.7%,4,2018-09-21,2018-12-20,Annapurna Pictures,False,200,<NA>,<NA>,<NA>,"$3,143,056",1141,"$3,143,056",Sep 21,Annapurna Pictures,False

#### Step 5: Dropping unnecessary columns from the merged data frame

With the data all combined, I can clean it up much easier since I am now working with one data frame instead of four. My next step will be to remove any unnecessary, empty, or duplicate columns.

In [16]:
# Defining the columns I want to drop
drop_columns = ['Genre_total', 'Budget_total', 'Running Time_total', 'Genre_calendar', 'Budget_calendar', 
                'Running Time_calendar', 'Distributor_calendar', 'Gross_total', 'Theaters', 'Release Date']
# Dropping all columns in the previously defined list
boxoffice_df.drop(columns=drop_columns, inplace=True)
# Checking the data frame
boxoffice_df

,Rank_total,Release,Max Th,Opening,% of Total,Open Th,Open,Close,Distributor_total,Estimated_total,Rank_calendar,Gross_calendar,Total Gross,Estimated_calendar
0,1,Spider-Man: No Way Home,4336,"$260,138,569",32.3%,4336,2021-12-17,2022-06-30,Sony Pictures Releasing,False,1,"$572,984,769","$804,793,477",False
1,2,Shang-Chi and the Legend of the Ten Rings,4300,"$75,388,688",33.6%,4300,2021-09-03,NaT,Walt Disney Studios Motion Pictures,False,2,"$224,543,292","$224,543,292",False
2,3,Venom: Let There Be Carnage,4225,"$90,033,210",42.2%,4225,2021-10-01,2022-01-27,Sony Pictures Releasing,False,3,"$212,609,036","$213,550,366",False
3,4,Black Widow,4275,"$80,366,312",43.8%,4160,2021-07-09,NaT,Walt Disney Studios Motion Pictures,False,4,"$183,651,655","$183,651,655",False
4,5,F9: The Fast Saga,4203,"$70,043,165",40.5%,4179,2021-06-25,NaT,Universal Pictures,False,5,"$173,005,945","$173,005,945",False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
685,179,"Juliet, Naked",467,"$60,886",1.8%,4,2018-08-17,2018-10-25,Roadside Attractions,False,193,"$3,444,895","$3,444,895",False
686,180,Bad Samaritan,2007,"$1,726,868",50.3%,2007,2018-05-04,2018-05-24,Electric Entertainment,False,194,"$3,435,047","$3,435,047",False
687,181,7 Days in Entebbe,838,"$1,592,645",47.9%,838,2018-03-16,2018-04-12,Focus Features,False,195,"$3,326,885","$3,326,885",False
688,183,2001: A Space Odyssey2018 Re-release,13,"$202,759",6.3%,4,2018-05-18,2018-07-15,Warner Bros.,False,197,"$3,236,321","$3,236,321",False
689,184,The Sisters Brothers,1141,"$115,575",3.7%,4,2018-09-21,2018-12-20,Annapurna Pictures,False,200,"$3,143,056","$3,143,056",False

#### Step 6: Replacing headers

Next, with dropping some columns I want to ensure the column headers still make sense. I am going to replace all of the column headers by first mapping the old names to the new names that I want to use and then apply it to the data frame by using rename():

In [17]:
# Creating a header_mapping variable that maps the old header names to the new ones I want to replace them with
header_mapping = {
    'Rank_total':'rank_total',
    'Release': 'title',
    'Max Th': 'max_theaters',
    'Opening': 'opening_gross',
    '% of Total': 'percent_of_total_gross',
    'Open Th': 'opening_theaters',
    'Open': 'release_date',
    'Close': 'closing_date',
    'Distributor_total': 'distributor',
    'Estimated_total': 'total_contains_estimates',
    'Rank_calendar': 'rank_calendar',
    'Gross_calendar': 'calendar_gross',
    'Total Gross': 'total_gross',
    'Estimated_calendar': 'calendar_contains_estimates'
}

In [18]:
#Using rename() to rename the headers using the previously mapped values
boxoffice_df.rename(columns=header_mapping, inplace=True)
boxoffice_df

,rank_total,title,max_theaters,opening_gross,percent_of_total_gross,opening_theaters,release_date,closing_date,distributor,total_contains_estimates,rank_calendar,calendar_gross,total_gross,calendar_contains_estimates
0,1,Spider-Man: No Way Home,4336,"$260,138,569",32.3%,4336,2021-12-17,2022-06-30,Sony Pictures Releasing,False,1,"$572,984,769","$804,793,477",False
1,2,Shang-Chi and the Legend of the Ten Rings,4300,"$75,388,688",33.6%,4300,2021-09-03,NaT,Walt Disney Studios Motion Pictures,False,2,"$224,543,292","$224,543,292",False
2,3,Venom: Let There Be Carnage,4225,"$90,033,210",42.2%,4225,2021-10-01,2022-01-27,Sony Pictures Releasing,False,3,"$212,609,036","$213,550,366",False
3,4,Black Widow,4275,"$80,366,312",43.8%,4160,2021-07-09,NaT,Walt Disney Studios Motion Pictures,False,4,"$183,651,655","$183,651,655",False
4,5,F9: The Fast Saga,4203,"$70,043,165",40.5%,4179,2021-06-25,NaT,Universal Pictures,False,5,"$173,005,945","$173,005,945",False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
685,179,"Juliet, Naked",467,"$60,886",1.8%,4,2018-08-17,2018-10-25,Roadside Attractions,False,193,"$3,444,895","$3,444,895",False
686,180,Bad Samaritan,2007,"$1,726,868",50.3%,2007,2018-05-04,2018-05-24,Electric Entertainment,False,194,"$3,435,047","$3,435,047",False
687,181,7 Days in Entebbe,838,"$1,592,645",47.9%,838,2018-03-16,2018-04-12,Focus Features,False,195,"$3,326,885","$3,326,885",False
688,183,2001: A Space Odyssey2018 Re-release,13,"$202,759",6.3%,4,2018-05-18,2018-07-15,Warner Bros.,False,197,"$3,236,321","$3,236,321",False
689,184,The Sisters Brothers,1141,"$115,575",3.7%,4,2018-09-21,2018-12-20,Annapurna Pictures,False,200,"$3,143,056","$3,143,056",False

#### Step 7: Rearranging columns

With all of these transformations and merging the order of the columns is no longer intuitive. To better organize my data set, I am going to take a minute to rearrange my columns in an order that makes the most sense:

In [19]:
# Rearranging the order of the columns of the data frame
boxoffice_df = boxoffice_df[['rank_total', 'rank_calendar', 'title', 'release_date', 'closing_date', 'total_gross', 'calendar_gross', 'opening_gross', 'percent_of_total_gross', 'opening_theaters', 'max_theaters', 'distributor', 'total_contains_estimates', 'calendar_contains_estimates']]
# Checking to data frame
boxoffice_df

,rank_total,rank_calendar,title,release_date,closing_date,total_gross,calendar_gross,opening_gross,percent_of_total_gross,opening_theaters,max_theaters,distributor,total_contains_estimates,calendar_contains_estimates
0,1,1,Spider-Man: No Way Home,2021-12-17,2022-06-30,"$804,793,477","$572,984,769","$260,138,569",32.3%,4336,4336,Sony Pictures Releasing,False,False
1,2,2,Shang-Chi and the Legend of the Ten Rings,2021-09-03,NaT,"$224,543,292","$224,543,292","$75,388,688",33.6%,4300,4300,Walt Disney Studios Motion Pictures,False,False
2,3,3,Venom: Let There Be Carnage,2021-10-01,2022-01-27,"$213,550,366","$212,609,036","$90,033,210",42.2%,4225,4225,Sony Pictures Releasing,False,False
3,4,4,Black Widow,2021-07-09,NaT,"$183,651,655","$183,651,655","$80,366,312",43.8%,4160,4275,Walt Disney Studios Motion Pictures,False,False
4,5,5,F9: The Fast Saga,2021-06-25,NaT,"$173,005,945","$173,005,945","$70,043,165",40.5%,4179,4203,Universal Pictures,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
685,179,193,"Juliet, Naked",2018-08-17,2018-10-25,"$3,444,895","$3,444,895","$60,886",1.8%,4,467,Roadside Attractions,False,False
686,180,194,Bad Samaritan,2018-05-04,2018-05-24,"$3,435,047","$3,435,047","$1,726,868",50.3%,2007,2007,Electric Entertainment,False,False
687,181,195,7 Days in Entebbe,2018-03-16,2018-04-12,"$3,326,885","$3,326,885","$1,592,645",47.9%,838,838,Focus Features,False,False
688,183,197,2001: A Space Odyssey2018 Re-release,2018-05-18,2018-07-15,"$3,236,321","$3,236,321","$202,759",6.3%,4,13,Warner Bros.,False,False
689,184,200,The Sisters Brothers,2018-09-21,2018-12-20,"$3,143,056","$3,143,056","$115,575",3.7%,4,1141,Annapurna Pictures,False,False

#### Step 8: Handling Re-releases

While scraping the tables from the web and working with the data frame, I noticed that a few of the films are re-releases. While on the web table this was denoted below the title, it seems that when scraped the year and the words "Re-Release" were tacked onto the title string. This could pose an issue when it comes to matching up films by title from all of my different data sources since having "Re-release" in the title would not make the films an exact match. To handle this I am going to coplete two major steps: first, I am going to create a seperate boolean column noting a film as a re-release based on the presence of the string "Re-release" in the title column. Once this data is preserved, I am going to use a regular expression to extract just the title of the film away from the year and re-release and keep just the title in the title column.

In [20]:
# Creating a boolean column 'rerelease' that populated True if the title column contains the string "Re-release"
boxoffice_df['rerelease'] = boxoffice_df['title'].str.contains('Re-release', case=False)
boxoffice_df

C:\Users\krist\AppData\Local\Temp\ipykernel_17364\3314713460.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  boxoffice_df['rerelease'] = boxoffice_df['title'].str.contains('Re-release', case=False)

,rank_total,rank_calendar,title,release_date,closing_date,total_gross,calendar_gross,opening_gross,percent_of_total_gross,opening_theaters,max_theaters,distributor,total_contains_estimates,calendar_contains_estimates,rerelease
0,1,1,Spider-Man: No Way Home,2021-12-17,2022-06-30,"$804,793,477","$572,984,769","$260,138,569",32.3%,4336,4336,Sony Pictures Releasing,False,False,False
1,2,2,Shang-Chi and the Legend of the Ten Rings,2021-09-03,NaT,"$224,543,292","$224,543,292","$75,388,688",33.6%,4300,4300,Walt Disney Studios Motion Pictures,False,False,False
2,3,3,Venom: Let There Be Carnage,2021-10-01,2022-01-27,"$213,550,366","$212,609,036","$90,033,210",42.2%,4225,4225,Sony Pictures Releasing,False,False,False
3,4,4,Black Widow,2021-07-09,NaT,"$183,651,655","$183,651,655","$80,366,312",43.8%,4160,4275,Walt Disney Studios Motion Pictures,False,False,False
4,5,5,F9: The Fast Saga,2021-06-25,NaT,"$173,005,945","$173,005,945","$70,043,165",40.5%,4179,4203,Universal Pictures,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
685,179,193,"Juliet, Naked",2018-08-17,2018-10-25,"$3,444,895","$3,444,895","$60,886",1.8%,4,467,Roadside Attractions,False,False,False
686,180,194,Bad Samaritan,2018-05-04,2018-05-24,"$3,435,047","$3,435,047","$1,726,868",50.3%,2007,2007,Electric Entertainment,False,False,False
687,181,195,7 Days in Entebbe,2018-03-16,2018-04-12,"$3,326,885","$3,326,885","$1,592,645",47.9%,838,838,Focus Features,False,False,False
688,183,197,2001: A Space Odyssey2018 Re-release,2018-05-18,2018-07-15,"$3,236,321","$3,236,321","$202,759",6.3%,4,13,Warner Bros.,False,False,True
689,184,200,The Sisters Brothers,2018-09-21,2018-12-20,"$3,143,056","$3,143,056","$115,575",3.7%,4,1141,Annapurna Pictures,False,False,False

In [21]:
# Looking at all rows where 'rerelease'=True to determine what regular expression to use
boxoffice_df[boxoffice_df['rerelease']]

,rank_total,rank_calendar,title,release_date,closing_date,total_gross,calendar_gross,opening_gross,percent_of_total_gross,opening_theaters,max_theaters,distributor,total_contains_estimates,calendar_contains_estimates,rerelease
141,149,149,Courageous10th Anniversary Re-release,2021-09-24,NaT,"$504,855","$504,855","$286,586",56.8%,1023,1023,Affirm Films,False,False,True
146,154,161,Top Gun2021 Re-release,2021-05-14,NaT,"$457,577","$408,937","$214,654",46.9%,153,153,Paramount Pictures,False,False,True
147,155,156,World War Z2021 Re-release,2021-05-28,NaT,"$448,000","$448,000","$347,000",<NA>,80,80,Paramount Pictures,True,False,True
155,163,163,Ghostbusters2021 Re-release,2021-10-29,NaT,"$391,718","$391,718","$304,317",77.7%,774,774,Sony Pictures Classics,False,False,True
165,174,172,The Emperor's New Groove2021 Re-release,2021-01-15,NaT,"$334,000","$334,000","$160,000",<NA>,744,744,Walt Disney Studios Motion Pictures,True,False,True
179,189,195,The Swimming Pool2021 Re-release,2021-05-14,NaT,"$211,467","$211,467","$3,867",1.8%,1,10,Rialto Distribution,False,False,True
181,192,197,Groundhog Day2021 Re-release,2021-01-29,NaT,"$200,989","$200,989","$85,330",42.5%,845,845,Sony Pictures Classics,False,False,True
224,40,53,Hocus Pocus2020 Re-release,2020-10-02,NaT,"$4,828,000","$4,828,000","$1,925,000",<NA>,2570,2570,Walt Disney Studios Motion Pictures,True,False,True
234,50,67,Star Wars: Episode V - The Empire Strikes Back...,2020-07-10,NaT,"$2,482,000","$2,482,000","$611,000",<NA>,611,2097,Walt Disney Studios Motion Pictures,True,False,True
236,52,69,The Nightmare Before Christmas2020 Re-release,2020-10-16,NaT,"$2,286,000","$2,286,000","$1,323,000",<NA>,2194,2194,Walt Disney Studios Motion Pictures,True,False,True
238,54,72,Elf2020 Re-release,2020-11-13,NaT,"$2,182,679","$1,975,000","$170,000",<NA>,300,850,New Line Cinema,True,False,True
244,60,79,Jurassic Park2020 Re-release,2020-06-19,NaT,"$1,386,600","$1,386,600","$517,600",<NA>,230,316,Universal Pictures,True,False,True
256,73,93,National Lampoon's Christmas Vacation2020 Re-r...,2020-11-25,NaT,"$871,000","$871,000","$170,000",<NA>,308,620,Warner Bros.,True,False,True
258,75,97,The Goonies2020 Re-release,2020-07-10,NaT,"$825,000","$825,000","$213,000",<NA>,134,457,Warner Bros.,True,False,True
262,79,101,Jaws2020 Re-release,2020-06-19,NaT,"$758,300","$758,300","$516,300",<NA>,187,187,Universal Pictures,True,False,True
264,81,105,Toy Story2020 Re-release,2020-11-06,NaT,"$727,000","$727,000","$505,000",<NA>,2102,2102,Walt Disney Studios Motion Pictures,True,False,True
265,82,106,"Monsters, Inc.2020 Re-release",2020-10-23,NaT,"$726,000","$726,000","$494,000",<NA>,1875,1875,Walt Disney Studios Motion Pictures,True,False,True
267,84,111,The Polar Express2020 Re-release,2020-12-04,NaT,"$711,000","$691,000","$155,000",<NA>,<NA>,450,Warner Bros.,True,False,True
268,85,108,The Santa Clause2020 Re-release,2020-11-20,NaT,"$706,000","$706,000","$461,000",<NA>,1581,1581,Walt Disney Studios Motion Pictures,True,False,True
271,88,113,The Addams Family2020 Re-release,2020-10-23,NaT,"$678,926","$678,926","$282,841",41.7%,1307,1307,United Artists Releasing,False,False,True
274,91,116,Ghostbusters2020 Re-release,2020-07-03,NaT,"$605,000","$605,000","$500,000",<NA>,622,622,Columbia Pictures,True,False,True
278,95,123,Guardians of the Galaxy2020 Re-release,2020-11-13,NaT,"$542,000","$542,000","$406,000",<NA>,1560,1560,Walt Disney Studios Motion Pictures,True,False,True
287,104,133,The Grinch2020 Re-release,2020-11-27,NaT,"$473,781","$502,781","$82,000",<NA>,<NA>,450,Universal Pictures,True,False,True
288,105,139,Beauty and the Beast2020 Re-release,2020-07-17,NaT,"$467,000","$467,000","$467,000",<NA>,527,527,Walt Disney Pictures,True,False,True
289,106,140,Inside Out2020 Re-release,2020-07-10,NaT,"$460,000","$460,000","$340,000",<NA>,442,442,Walt Disney Pictures,True,False,True
293,112,143,Iron Man2020 Re-release,2020-07-17,NaT,"$430,000","$430,000","$430,000",<NA>,462,462,Walt Disney Pictures,True,False,True
295,114,166,How the Grinch Stole Christmas2020 Re-release,2020-12-04,NaT,"$420,180","$294,000",<NA>,<NA>,<NA>,300,Universal Pictures,False,False,True
302,121,149,Black Panther2020 Re-release,2020-07-10,NaT,"$367,000","$367,000","$367,000",<NA>,421,421,Walt Disney Pictures,True,False,True
307,126,157,Die Hard2020 Re-release,2020-12-04,NaT,"$325,000","$325,000","$189,000",<NA>,1172,1172,Walt Disney Studios Motion Pictures,True,False,True
312,131,165,Gremlins2020 Re-release,2020-07-10,NaT,"$295,000","$295,000","$140,000",<NA>,59,64,<NA>,True,False,True
316,135,170,An American in Paris2020 Re-release,2020-01-19,NaT,"$267,824","$267,824","$182,606",68.2%,651,651,Fathom Events,False,False,True
317,137,171,Wonder Woman2020 Re-release,2020-12-11,NaT,"$252,000","$252,000","$189,000",<NA>,<NA>,560,Warner Bros.,True,False,True
318,138,172,Back to the Future2020 Re-release,2020-07-31,NaT,"$247,000","$247,000","$107,000",<NA>,116,258,Universal Pictures,True,False,True
319,140,173,Bohemian Rhapsody2020 Re-release,2020-07-17,NaT,"$240,000","$240,000","$240,000",<NA>,<NA>,<NA>,Twentieth Century Fox,True,False,True
320,141,175,Tokyo Godfathers2020 Re-release,2020-03-09,NaT,"$237,571","$237,581","$5,800",2.4%,4,519,Fathom Events,False,False,True
324,145,180,Frozen2020 Re-release,2020-11-25,NaT,"$215,000","$215,000","$120,000",<NA>,1367,1367,Walt Disney Studios Motion Pictures,True,False,True
329,150,186,National Theater Live: Cyrano de Bergerac2020 ...,2020-02-20,NaT,"$198,352","$198,352",<NA>,<NA>,<NA>,472,Fathom Events,False,False,True
510,175,195,Arctic2019 Re-release,2019-02-01,2019-05-09,"$2,410,795","$2,410,795","$50,878",2.1%,4,268,Bleecker Street Media,False,False,True
661,150,167,Once Upon a Deadpool2018 Re-release,2018-12-12,2019-01-24,"$6,100,309","$6,016,007","$2,683,200",44%,1566,1566,Twentieth Century Fox,False,False,True
688,183,197,2001: A Space Odyssey2018 Re-release,2018-05-18,2018-07-15,"$3,236,321","$3,236,321","$202,759",6.3%,4,13,Warner Bros.,False,False,True

In [22]:
# Defining a regular expression pattern to capture the title without the re-release info
regex_pattern = r'^(.*?)(?:\d{4} Re-release|10th Anniversary Re-release)?$'

# Extracting the title without the re-release info using str.extract()
boxoffice_df['title'] = boxoffice_df['title'].str.extract(regex_pattern, expand=False).str.strip()

# Checking that the extraction worked correctly
boxoffice_df[boxoffice_df['rerelease']]

C:\Users\krist\AppData\Local\Temp\ipykernel_17364\3966644205.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  boxoffice_df['title'] = boxoffice_df['title'].str.extract(regex_pattern, expand=False).str.strip()

,rank_total,rank_calendar,title,release_date,closing_date,total_gross,calendar_gross,opening_gross,percent_of_total_gross,opening_theaters,max_theaters,distributor,total_contains_estimates,calendar_contains_estimates,rerelease
141,149,149,Courageous,2021-09-24,NaT,"$504,855","$504,855","$286,586",56.8%,1023,1023,Affirm Films,False,False,True
146,154,161,Top Gun,2021-05-14,NaT,"$457,577","$408,937","$214,654",46.9%,153,153,Paramount Pictures,False,False,True
147,155,156,World War Z,2021-05-28,NaT,"$448,000","$448,000","$347,000",<NA>,80,80,Paramount Pictures,True,False,True
155,163,163,Ghostbusters,2021-10-29,NaT,"$391,718","$391,718","$304,317",77.7%,774,774,Sony Pictures Classics,False,False,True
165,174,172,The Emperor's New Groove,2021-01-15,NaT,"$334,000","$334,000","$160,000",<NA>,744,744,Walt Disney Studios Motion Pictures,True,False,True
179,189,195,The Swimming Pool,2021-05-14,NaT,"$211,467","$211,467","$3,867",1.8%,1,10,Rialto Distribution,False,False,True
181,192,197,Groundhog Day,2021-01-29,NaT,"$200,989","$200,989","$85,330",42.5%,845,845,Sony Pictures Classics,False,False,True
224,40,53,Hocus Pocus,2020-10-02,NaT,"$4,828,000","$4,828,000","$1,925,000",<NA>,2570,2570,Walt Disney Studios Motion Pictures,True,False,True
234,50,67,Star Wars: Episode V - The Empire Strikes Back,2020-07-10,NaT,"$2,482,000","$2,482,000","$611,000",<NA>,611,2097,Walt Disney Studios Motion Pictures,True,False,True
236,52,69,The Nightmare Before Christmas,2020-10-16,NaT,"$2,286,000","$2,286,000","$1,323,000",<NA>,2194,2194,Walt Disney Studios Motion Pictures,True,False,True
238,54,72,Elf,2020-11-13,NaT,"$2,182,679","$1,975,000","$170,000",<NA>,300,850,New Line Cinema,True,False,True
244,60,79,Jurassic Park,2020-06-19,NaT,"$1,386,600","$1,386,600","$517,600",<NA>,230,316,Universal Pictures,True,False,True
256,73,93,National Lampoon's Christmas Vacation,2020-11-25,NaT,"$871,000","$871,000","$170,000",<NA>,308,620,Warner Bros.,True,False,True
258,75,97,The Goonies,2020-07-10,NaT,"$825,000","$825,000","$213,000",<NA>,134,457,Warner Bros.,True,False,True
262,79,101,Jaws,2020-06-19,NaT,"$758,300","$758,300","$516,300",<NA>,187,187,Universal Pictures,True,False,True
264,81,105,Toy Story,2020-11-06,NaT,"$727,000","$727,000","$505,000",<NA>,2102,2102,Walt Disney Studios Motion Pictures,True,False,True
265,82,106,"Monsters, Inc.",2020-10-23,NaT,"$726,000","$726,000","$494,000",<NA>,1875,1875,Walt Disney Studios Motion Pictures,True,False,True
267,84,111,The Polar Express,2020-12-04,NaT,"$711,000","$691,000","$155,000",<NA>,<NA>,450,Warner Bros.,True,False,True
268,85,108,The Santa Clause,2020-11-20,NaT,"$706,000","$706,000","$461,000",<NA>,1581,1581,Walt Disney Studios Motion Pictures,True,False,True
271,88,113,The Addams Family,2020-10-23,NaT,"$678,926","$678,926","$282,841",41.7%,1307,1307,United Artists Releasing,False,False,True
274,91,116,Ghostbusters,2020-07-03,NaT,"$605,000","$605,000","$500,000",<NA>,622,622,Columbia Pictures,True,False,True
278,95,123,Guardians of the Galaxy,2020-11-13,NaT,"$542,000","$542,000","$406,000",<NA>,1560,1560,Walt Disney Studios Motion Pictures,True,False,True
287,104,133,The Grinch,2020-11-27,NaT,"$473,781","$502,781","$82,000",<NA>,<NA>,450,Universal Pictures,True,False,True
288,105,139,Beauty and the Beast,2020-07-17,NaT,"$467,000","$467,000","$467,000",<NA>,527,527,Walt Disney Pictures,True,False,True
289,106,140,Inside Out,2020-07-10,NaT,"$460,000","$460,000","$340,000",<NA>,442,442,Walt Disney Pictures,True,False,True
293,112,143,Iron Man,2020-07-17,NaT,"$430,000","$430,000","$430,000",<NA>,462,462,Walt Disney Pictures,True,False,True
295,114,166,How the Grinch Stole Christmas,2020-12-04,NaT,"$420,180","$294,000",<NA>,<NA>,<NA>,300,Universal Pictures,False,False,True
302,121,149,Black Panther,2020-07-10,NaT,"$367,000","$367,000","$367,000",<NA>,421,421,Walt Disney Pictures,True,False,True
307,126,157,Die Hard,2020-12-04,NaT,"$325,000","$325,000","$189,000",<NA>,1172,1172,Walt Disney Studios Motion Pictures,True,False,True
312,131,165,Gremlins,2020-07-10,NaT,"$295,000","$295,000","$140,000",<NA>,59,64,<NA>,True,False,True
316,135,170,An American in Paris,2020-01-19,NaT,"$267,824","$267,824","$182,606",68.2%,651,651,Fathom Events,False,False,True
317,137,171,Wonder Woman,2020-12-11,NaT,"$252,000","$252,000","$189,000",<NA>,<NA>,560,Warner Bros.,True,False,True
318,138,172,Back to the Future,2020-07-31,NaT,"$247,000","$247,000","$107,000",<NA>,116,258,Universal Pictures,True,False,True
319,140,173,Bohemian Rhapsody,2020-07-17,NaT,"$240,000","$240,000","$240,000",<NA>,<NA>,<NA>,Twentieth Century Fox,True,False,True
320,141,175,Tokyo Godfathers,2020-03-09,NaT,"$237,571","$237,581","$5,800",2.4%,4,519,Fathom Events,False,False,True
324,145,180,Frozen,2020-11-25,NaT,"$215,000","$215,000","$120,000",<NA>,1367,1367,Walt Disney Studios Motion Pictures,True,False,True
329,150,186,National Theater Live: Cyrano de Bergerac,2020-02-20,NaT,"$198,352","$198,352",<NA>,<NA>,<NA>,472,Fathom Events,False,False,True
510,175,195,Arctic,2019-02-01,2019-05-09,"$2,410,795","$2,410,795","$50,878",2.1%,4,268,Bleecker Street Media,False,False,True
661,150,167,Once Upon a Deadpool,2018-12-12,2019-01-24,"$6,100,309","$6,016,007","$2,683,200",44%,1566,1566,Twentieth Century Fox,False,False,True
688,183,197,2001: A Space Odyssey,2018-05-18,2018-07-15,"$3,236,321","$3,236,321","$202,759",6.3%,4,13,Warner Bros.,False,False,True

### Printing and Exporting the Final Data Set

In [23]:
# Displaying final data set
display(boxoffice_df)

,rank_total,rank_calendar,title,release_date,closing_date,total_gross,calendar_gross,opening_gross,percent_of_total_gross,opening_theaters,max_theaters,distributor,total_contains_estimates,calendar_contains_estimates,rerelease
0,1,1,Spider-Man: No Way Home,2021-12-17,2022-06-30,"$804,793,477","$572,984,769","$260,138,569",32.3%,4336,4336,Sony Pictures Releasing,False,False,False
1,2,2,Shang-Chi and the Legend of the Ten Rings,2021-09-03,NaT,"$224,543,292","$224,543,292","$75,388,688",33.6%,4300,4300,Walt Disney Studios Motion Pictures,False,False,False
2,3,3,Venom: Let There Be Carnage,2021-10-01,2022-01-27,"$213,550,366","$212,609,036","$90,033,210",42.2%,4225,4225,Sony Pictures Releasing,False,False,False
3,4,4,Black Widow,2021-07-09,NaT,"$183,651,655","$183,651,655","$80,366,312",43.8%,4160,4275,Walt Disney Studios Motion Pictures,False,False,False
4,5,5,F9: The Fast Saga,2021-06-25,NaT,"$173,005,945","$173,005,945","$70,043,165",40.5%,4179,4203,Universal Pictures,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
685,179,193,"Juliet, Naked",2018-08-17,2018-10-25,"$3,444,895","$3,444,895","$60,886",1.8%,4,467,Roadside Attractions,False,False,False
686,180,194,Bad Samaritan,2018-05-04,2018-05-24,"$3,435,047","$3,435,047","$1,726,868",50.3%,2007,2007,Electric Entertainment,False,False,False
687,181,195,7 Days in Entebbe,2018-03-16,2018-04-12,"$3,326,885","$3,326,885","$1,592,645",47.9%,838,838,Focus Features,False,False,False
688,183,197,2001: A Space Odyssey,2018-05-18,2018-07-15,"$3,236,321","$3,236,321","$202,759",6.3%,4,13,Warner Bros.,False,False,True
689,184,200,The Sisters Brothers,2018-09-21,2018-12-20,"$3,143,056","$3,143,056","$115,575",3.7%,4,1141,Annapurna Pictures,False,False,False

In [24]:
# Exporting to .csv
boxoffice_df.to_csv('boxoffice.csv', index=False)

### Ethical Considerations of this Data Wrangling

Scraping data from a website is a completely new process to me, and there are some unique ethical considerations to take into account when collecting data in this manner. For this particular process, I needed to make multiple calls to the same website in order to parse out data from the html of multiple different tables on multiple different pages. While I do not believe that the requests I was making were overcomplicated and putting too much load on the website, it is definitely important to keep in mind the number of times you call to a certain website and the complication of the ask you are sending it so as not to overload the website's servers. I also ensured that I interacted with the website in a way that did not overwhelm their terms of service.

I also chose my data carefully to ensure there was a wide and inclusive representation of films that I pulled data for. For example, I ensured that the data tables I scraped included information for both wide- and limited-release films, allowing more space for special and independent films to have representation in the data. I also ensured that I combined multiple tables that held different information on gross, calendar-year, and opening-weekend earnings to ensure I have multiple different potential measures of film success at the boxoffice. All transformations that I  completed for my data are well-documented, and any transformations that posed the risk for potential loss of important data were accounted for and addressed prior to completing the transformation (for example, preserving whether or not a film was a re-release before stripping that information from the title column). Overall, the transformations I completed for this data were straightforward and well-documented, I ensured I stayed within the website's terms of service and limited my calls to their servers, and I ensured as diverse of a representation of films in the data set as I could with the information available to me.